on:
  push:
    branches:
      - main
env:
  ORGANIZATION: 'kelalab'
  DOCKERFILE: 'Dockerfile'
  IMAGENAME: 'doccano-gui'
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build "$GITHUB_WORKSPACE" -f  ${{ env.DOCKERFILE }} -t ghcr.io/${{env.ORGANIZATION}}/${{ env.IMAGENAME }}:${{ github.sha }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push webhook image to ghcr
        run: |
          docker tag ghcr.io/${{env.ORGANIZATION}}/${{ env.IMAGENAME }}:${{ github.sha }} ghcr.io/${{env.ORGANIZATION}}/${{ env.IMAGENAME }}:latest
          docker push ghcr.io/${{env.ORGANIZATION}}/${{ env.IMAGENAME }}:latest
